### ISSUE TITLE
TypeScript 5.0 Breaking Changes

### ISSUE THREAD

**Issue by tommy-mitchell** [SamVerschueren/tsd-typescript#5]
https://github.com/microsoft/TypeScript-wiki/blob/main/API-Breaking-Changes.md#typescript-50

TypeScript is moving from namespaces to modules in TS 5.0:

> The output files have changed significantly; if you are patching TypeScript, you will definitely need to change your patches.

**Comment by SamVerschueren** [comment]
Not sure if anything else is impacted, but it looks like the only change I needed to make was changing `var` to `const` in my replacements https://github.com/SamVerschueren/tsd-typescript/commit/e80506b3036d0809220d0d04ddd4a59380122c03.

And I also had to upgrade my GitHub Actions to run on Node.js 16. Latest patched TypeScript is now released. 🎉
