### ISSUE TITLE
No longer updates

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/tsd-typescript#6]
Last version was 5.3.3. Latest TS is 5.4.2.

// @SamVerschueren

**Comment by SamVerschueren** [comment]
I'll try to have a look tomorrow. Thanks for notifying!

**Comment by uhyo** [comment]
@SamVerschueren Hi, maybe this restriction was hit:

> In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. 
>
> https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule:~:text=In%20a%20public%20repository%2C%20scheduled%20workflows%20are%20automatically%20disabled%20when%20no%20repository%20activity%20has%20occurred%20in%2060%20days.%20For%20information%20on%20re%2Denabling%20a%20disabled%20workflow%2C%20see%20%22Disabling%20and%20enabling%20a%20workflow.%22

Docs suggest that re-enabling the Upgrade workflow should work. Hope you can give it a try 🙂

https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow

**Comment by SamVerschueren** [comment]
Apparently they now expose `isAssignableTo` themselves. So the tests didn't work anymore. Fixed it by removing the patch code but kept the tests to make sure they don't remove it again in the future.
